name: Django + pytest

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    # Django 6.0 wymaga Pythona >= 3.12
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: mysite.settings

        run: |
          python manage.py migrate --noinput

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: mysite.settings
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        run: |
          pytest -q
